/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TextRouteImport } from './routes/text'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as FilesRouteImport } from './routes/files'
import { Route as CollisionsRouteImport } from './routes/collisions'
import { Route as IndexRouteImport } from './routes/index'

const TextRoute = TextRouteImport.update({
  id: '/text',
  path: '/text',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const CollisionsRoute = CollisionsRouteImport.update({
  id: '/collisions',
  path: '/collisions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collisions': typeof CollisionsRoute
  '/files': typeof FilesRoute
  '/learn': typeof LearnRoute
  '/text': typeof TextRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collisions': typeof CollisionsRoute
  '/files': typeof FilesRoute
  '/learn': typeof LearnRoute
  '/text': typeof TextRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collisions': typeof CollisionsRoute
  '/files': typeof FilesRoute
  '/learn': typeof LearnRoute
  '/text': typeof TextRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/collisions' | '/files' | '/learn' | '/text'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/collisions' | '/files' | '/learn' | '/text'
  id: '__root__' | '/' | '/collisions' | '/files' | '/learn' | '/text'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollisionsRoute: typeof CollisionsRoute
  FilesRoute: typeof FilesRoute
  LearnRoute: typeof LearnRoute
  TextRoute: typeof TextRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/text': {
      id: '/text'
      path: '/text'
      fullPath: '/text'
      preLoaderRoute: typeof TextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collisions': {
      id: '/collisions'
      path: '/collisions'
      fullPath: '/collisions'
      preLoaderRoute: typeof CollisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollisionsRoute: CollisionsRoute,
  FilesRoute: FilesRoute,
  LearnRoute: LearnRoute,
  TextRoute: TextRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
